services:
  storefront:
    build:
      context: ./storefront
    ports:
      - "3000:3000"
    env_file:
      - ./storefront/.env.local
    command: npm run dev

  admin:
    build:
      context: ./admin
    ports:
      - "3001:3000"
    env_file:
      - ./admin/.env.local
    command: npm run dev